In [ ]:
import pandas as pd
import os

UsageError: Line magic function `%%` not found.

In [ ]:

file_path = "..\\cleaned_data\\annotation\\CalMS21_supplemental.parquet"
df = pd.read_parquet(file_path) 
df

       agent_id  target_id        action  start_frame  stop_frame
0             1          2         sniff           66          75
1             1          2         sniff         1946        2035
2             1          2  sniffgenital         2036        2153
3             1          2         sniff         2425        2476
4             1          2  attemptmount         2477        2492
...         ...        ...           ...          ...         ...
30863         1          2     sniffface         3164        3174
30864         1          2     sniffface         3469        3515
30865         1          2     sniffface         3598        3604
30866         1          2      approach         3913        3927
30867         1          2     sniffbody         3928        3934

[30868 rows x 5 columns]

In [14]:
file_path = "..\\cleaned_data\\tracking\\CalMS21_supplemental.parquet"
df = pd.read_parquet(file_path)
df

          video_frame  mouse_id   bodypart           x           y
0                   0         1   ear_left  822.076599  440.140015
1                   0         1  ear_right  792.076599  511.140015
2                   0         1   hip_left  877.076599  446.140015
3                   0         1  hip_right  859.076599  526.140015
4                   0         1       neck  822.076599  480.140015
...               ...       ...        ...         ...         ...
77672023         4860         2   hip_left  800.437744  148.148438
77672024         4860         2  hip_right  873.437744  161.148438
77672025         4860         2       neck  819.437744  203.148438
77672026         4860         2       nose  791.437744  257.148438
77672027         4860         2  tail_base  826.437744  121.148430

[77672028 rows x 5 columns]